spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  sql:
    init:
      mode: always
